### ISSUE TITLE
Rulesets can't be included in commands

### ISSUE THREAD

**Issue by Alex47856** [No3371/obsidian-regex-pipeline#18]
There are only two entries in commands
1. RegEx Pipeline: Undifined (not working)
2. RegEx Pipeline: Apply Ruleset

I would like to add RegEx Rulesets to create Macros using another plugin.
But it can't be implemented without inputs in commands.

**Comment by No3371** [comment]
Please enable commands in the plugin settings.

**Comment by XMB-7** [comment]
Just found that with the following config, rules are not only disappear in the right click manu but also in the command palette, whcih is not as expected.
![image](https://user-images.githubusercontent.com/65625632/211189433-ebeaaf82-eba6-4096-836d-f2c2d774afd2.png)
![image](https://user-images.githubusercontent.com/65625632/211189629-0d3bf9ce-ab5c-4913-bce6-51cf5f59dde5.png)

**Comment by No3371** [comment]
The quick-rule slider is dragged to the left most, which is zero. So no quick-rule. 
Commands are just quick-rules in command form.

**Comment by XMB-7** [comment]
My expectation is no rules in right-click menu but all rules still available as obsidian commands. Is it possible to achieve?
For example, I've made 10 rules, and I only want the ninth to be integrated into a macro as an obsidian command using the QuickAdd plugin. In this case, I have to drag the slider to 10, otherwise, the specific rule doesn't show up in the command palette.

**Comment by No3371** [comment]
Unfortunately no. Maybe in next update.

**Comment by No3371** [comment]
@XMB-7 In 1.4 the count of commands and menu items are now separately configurable.

As for the original issue, due to lack of activity, I'm closing this.

**Comment by XMB-7** [comment]
Thanks for your time and effort, it helps me a lot.
