### ISSUE TITLE
Is it posssible to exclude some folders?

### ISSUE THREAD

**Issue by ooker777** [No3371/obsidian-regex-pipeline#9]
Or even better, notes with tags or other patterns

**Comment by No3371** [comment]
I don't get it, the plugin helps you do regex replacements on current opened file, what's it doing to your files/folders?

**Comment by ooker777** [comment]
Oh I see. I thought it replaces in all notes. So may I ask why didn't you
make that feature as well?

**Comment by No3371** [comment]
Because it's made to help me authoring my knowledge database, the only purpose of the plugin is to reduce repetitive manual modification.

So the feature you describe is out of scope; and just as you said, a "replace in all" feature requires additional filtering mechanic which involve more logical and UI change. Hence "replace in all" will not be added.

**Comment by ooker777** [comment]
Do you think we should make it clear that this plugin will only replace strings in the current open note?

**Comment by No3371** [comment]
No, it should be intuitive enough to Obsidian users that a plugin do something to the opened note when nothing otherwise mentioned.

**Comment by ooker777** [comment]
I mean one of the reason i download this plugin is to be able to replace all the vault. So I think there are some people have the same thought too

**Comment by No3371** [comment]
For that exact purpose I suggest a better solution: VSCode. It fully supports Regex and should have even better performance.

Open the folder in VSCode, `Ctrl+Shift+F` (default shortcut), you will see this (The appearance may vary by theme):

![圖片](https://user-images.githubusercontent.com/1814971/164883164-8d4f665d-f2ac-45f7-9db7-4e3e0e0ea1c7.png)

Include `*.md` should works because notes are markdown files.
